# <font color=steelblue>快速创建数组</font>

In [1]:
import numpy as np

In [2]:
np.random.randn(10)

array([ 0.79238893, -0.84318622,  0.89187999,  1.16545221, -1.41480849,
       -2.27964728, -0.97371126, -0.23306998, -0.74399892, -2.77959282])

In [3]:
np.random.randint(3,10,size=(2,3))

array([[8, 7, 3],
       [9, 7, 8]])

In [4]:
np.random.randint(10,size=20).reshape(4,5)

array([[7, 1, 0, 2, 0],
       [5, 2, 0, 8, 1],
       [1, 0, 9, 0, 6],
       [7, 6, 0, 6, 4]])

# <font color=steelblue>数组运算</font>

In [5]:
a = np.random.randint(10,size=6).reshape(2,3)
b = np.random.randint(10,size=6).reshape(2,3)

In [6]:
a

array([[6, 9, 9],
       [5, 1, 7]])

In [7]:
b

array([[3, 9, 9],
       [4, 6, 4]])

In [8]:
a+b

array([[ 9, 18, 18],
       [ 9,  7, 11]])

In [9]:
a-b

array([[ 3,  0,  0],
       [ 1, -5,  3]])

In [10]:
a*b

array([[18, 81, 81],
       [20,  6, 28]])

In [11]:
a/b

array([[2.        , 1.        , 1.        ],
       [1.25      , 0.16666667, 1.75      ]])

# <font color=steelblue>矩阵的运算</font>

In [12]:
A = np.mat(a)
B = np.mat(b)

In [13]:
A

matrix([[6, 9, 9],
        [5, 1, 7]])

In [14]:
B

matrix([[3, 9, 9],
        [4, 6, 4]])

In [15]:
A+B

matrix([[ 9, 18, 18],
        [ 9,  7, 11]])

In [16]:
A-B

matrix([[ 3,  0,  0],
        [ 1, -5,  3]])

In [17]:
A*B.T

matrix([[180, 114],
        [ 87,  54]])

In [18]:
A/B

matrix([[2.        , 1.        , 1.        ],
        [1.25      , 0.16666667, 1.75      ]])

# <font color=steelblue>Array常用函数</font>

In [19]:
a

array([[6, 9, 9],
       [5, 1, 7]])

In [20]:
np.unique(a)

array([1, 5, 6, 7, 9])

In [21]:
sum(a)

array([11, 10, 16])

In [22]:
a.sum()

37

In [23]:
sum(a[:,0:2])

array([11, 10])

In [24]:
max(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [25]:
a.max()

9