# <font color=steelBlue>创建数组</font>

In [1]:
import numpy as np

In [2]:
#create from python list
list_1 = [1,2,3,4]
list_2 = [5,6,7,8]

In [3]:
array_1 = np.array(list_1)
array_1

array([1, 2, 3, 4])

In [4]:
array_2 = np.array([list_1,list_2])
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
array_2.shape

(2, 4)

In [6]:
array_2.size

8

In [7]:
array_2.dtype

dtype('int64')

In [8]:
array_3 = np.array([[1.0,2,3],[4.0,5,6]])
array_3.dtype

dtype('float64')

In [9]:
array_4 = np.arange(1,10,2)
array_4

array([1, 3, 5, 7, 9])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.eye(5).dtype

dtype('float64')

# <font color=steelBlue>索引访问</font>

In [14]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a[1:5]

array([2, 3, 4, 5])

In [16]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [17]:
b = np.array([[1,2,3],[4,5,6]])

In [18]:
b[::-1,(0,1)]

array([[4, 5],
       [1, 2]])