# <font color=steelblue>使用pickle序列化array</font>

In [1]:
import pickle
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
f = open('x.pkl','wb')
pickle.dump(x,f)

In [4]:
!ls

Array的创建与访问.ipynb       two_array.npz
Array的输入和输出.ipynb       x.pkl
one_array.npy                 数组与矩阵运算.ipynb


In [5]:
f = open('x.pkl','rb')
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# <font color=steelblue>使用numpy自带函数实现</font>

In [6]:
np.save('one_array',x)

In [7]:
!ls

Array的创建与访问.ipynb       two_array.npz
Array的输入和输出.ipynb       x.pkl
one_array.npy                 数组与矩阵运算.ipynb


In [8]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
y = np.arange(20)
np.savez('two_array',a=x,two=y)

In [10]:
!ls

Array的创建与访问.ipynb       two_array.npz
Array的输入和输出.ipynb       x.pkl
one_array.npy                 数组与矩阵运算.ipynb


In [11]:
c = np.load('two_array.npz')

In [12]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
c['two']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])