In [1]:
import numpy as np
import pandas as pd

In [2]:
lst = [6,8,10,15,16,24,25,40,67]

In [3]:
#离散化
pd.qcut(lst,q=3)#等比切分

[(5.999, 13.333], (5.999, 13.333], (5.999, 13.333], (13.333, 24.333], (13.333, 24.333], (13.333, 24.333], (24.333, 67.0], (24.333, 67.0], (24.333, 67.0]]
Categories (3, interval[float64]): [(5.999, 13.333] < (13.333, 24.333] < (24.333, 67.0]]

In [4]:
pd.cut(lst,bins=3)#等距切分

[(5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (5.939, 26.333], (26.333, 46.667], (46.667, 67.0]]
Categories (3, interval[float64]): [(5.939, 26.333] < (26.333, 46.667] < (46.667, 67.0]]

In [5]:
pd.cut(lst,bins=4,labels=['low','medium','high','very high'],retbins=True)

([low, low, low, low, low, medium, medium, high, very high]
 Categories (4, object): [low < medium < high < very high],
 array([ 5.939, 21.25 , 36.5  , 51.75 , 67.   ]))

In [6]:
#归一化与标准化
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [7]:
MinMaxScaler().fit_transform(np.array([1,4,10,15,21]).reshape(-1,1))

array([[0.  ],
       [0.15],
       [0.45],
       [0.7 ],
       [1.  ]])

In [8]:
StandardScaler().fit_transform(np.array([1,1,1,1,0,0,0,0]).reshape(-1,1))

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [9]:
StandardScaler().fit_transform(np.array([1,0,0,0,0,0,0,0]).reshape(-1,1))

array([[ 2.64575131],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447],
       [-0.37796447]])

In [42]:
#标签化与独热编码
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
LabelEncoder().fit_transform(np.array(['Down','Down','Up','Down','Up'])
                             .reshape(-1,1))

array([0, 0, 1, 0, 1])

In [39]:
lb_encoder = LabelEncoder().fit(np.array(['Red','Yellow','Blue','Green']))
lb_trans_f1 = lb_Encoder.transform(np.array(['Yellow','Green','Red','Blue']))
lb_trans_f1

array([3, 1, 2, 0])

In [40]:
oht_encoder= OneHotEncoder().fit(lb_trans_f1.reshape(-1,1))
lb_trans_f2= lb_encoder.transform(np.array(['Blue','Green','Red','Yellow']))
oht_encoder.transform(lb_trans_f2.reshape(-1,1)).toarray()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
#规范化
from sklearn.preprocessing import Normalizer
Normalizer(norm='l1').fit_transform([[1,1,3,-1,2]])

array([[ 0.125,  0.125,  0.375, -0.125,  0.25 ]])

In [36]:
Normalizer(norm='l2').fit_transform([[1,1,3,-1,2]])

array([[ 0.25,  0.25,  0.75, -0.25,  0.5 ]])

In [37]:
#LDA降维
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
X = np.array([[-1,-1],[-2,-1],[-3,-2],[1,1],[2,1],[3,2]])
y = np.array([0,0,0,1,1,1])
clf = LinearDiscriminantAnalysis().fit(X,y)
clf.predict([[-0.8,-1]])

array([0])